### ISSUE TITLE
Editor not working. Showing regular textarea field

### ISSUE THREAD

**Issue by mamun724682** [F-loat/vue-simplemde#114] opened 2022-01-02 11:55 UTC
Please check your sample https://f-loat.github.io/vue-simplemde/dist/demo.html

And it's showing this console error
![image](https://user-images.githubusercontent.com/41566116/147874939-e60fa4cd-4bfa-44b8-898f-c14cc9a255f0.png)

**Comment by staszek998** [comment] 2022-01-03 08:21
@mamun724682, this bug is caused by the `marked` NPM package in version `4+`. For more information, please see the [pull request #111](https://github.com/F-loat/vue-simplemde/pull/111) in this repo (✅ merged, ❌ not published yet) and the [pull request #825](https://github.com/sparksuite/simplemde-markdown-editor/pull/825) in the SimpleMDE's repo (❌ not merged, ❌ not published).

**Comment by F-loat** [comment] 2022-01-11 03:01
v2.0.1 published

**Closed by F-loat** 2022-01-11 03:01 UTC
